use airline;

INSERT INTO airline VALUES('AA', 'American Airlines', 'United States');
INSERT INTO airline VALUES('AC', 'Air Canada', 'Canada');
INSERT INTO airline VALUES('AD', 'Azul Linhas Aéreas Brasileiras', 'Brazil');
INSERT INTO airline VALUES('AE', 'Mandarin Airlines', 'Taiwan');
INSERT INTO airline VALUES('AF', 'Air France', 'France');
INSERT INTO airline VALUES('AG', 'ASL Airlines Ireland', 'Ireland');
INSERT INTO airline VALUES('AH', 'Air Algérie', 'Algeria');
INSERT INTO airline VALUES('AK', 'AirAsia', 'Malaysia');
INSERT INTO airline VALUES('AL', 'Skywalk Airlines', 'United States');
INSERT INTO airline VALUES('AM', 'Aeroméxico', 'Mexico');
INSERT INTO airline VALUES('AN', 'Advanced Air', 'United States');
INSERT INTO airline VALUES('AO', 'Australian Airlines', 'Australia');
INSERT INTO airline VALUES('AP', 'AlbaStar', 'Spain');
INSERT INTO airline VALUES('AQ', '9 Air', 'China');
INSERT INTO airline VALUES('AR', 'Aerolíneas Argentinas', 'Argentina');
INSERT INTO airline VALUES('AS', 'Alaska Airlines, Inc.', 'United States');
INSERT INTO airline VALUES('AT', 'Royal Air Maroc', 'Morocco');
INSERT INTO airline VALUES('AU', 'Austral Líneas Aéreas', 'Argentina');
INSERT INTO airline VALUES('AV', 'Avianca', 'Colombia');
INSERT INTO airline VALUES('AW', 'Africa World Airlines', 'Ghana');
INSERT INTO airline VALUES('AX', 'Trans States Airlines', 'United States');
INSERT INTO airline VALUES('AY', 'Finnair', 'Finland');
INSERT INTO airline VALUES('AZ', 'ITA Airways', 'Italy');
INSERT INTO airline VALUES('BA', 'British Airways', 'United Kingdom');
INSERT INTO airline VALUES('BB', 'Seaborne Airlines', 'United States');
INSERT INTO airline VALUES('BC', 'Skymark Airlines', 'Japan');
INSERT INTO airline VALUES('BE', 'Flybe', 'United Kingdom');
INSERT INTO airline VALUES('BF', 'MarkAir', 'United States');
INSERT INTO airline VALUES('BG', 'Biman Bangladesh Airlines', 'Bangladesh');
INSERT INTO airline VALUES('BI', 'Royal Brunei Airlines', 'Brunei');
INSERT INTO airline VALUES('BJ', 'Nouvel Air Tunisie', 'Tunisia');
INSERT INTO airline VALUES('BK', 'Potomac Air', 'United States');
INSERT INTO airline VALUES('BL', 'Pacific Airlines', 'Vietnam');
INSERT INTO airline VALUES('BM', 'BMI Regional', 'United Kingdom');
INSERT INTO airline VALUES('BN', 'Forward Air International Airlines', 'United States');
INSERT INTO airline VALUES('BO', 'Bluebird Nordic', 'Iceland');
INSERT INTO airline VALUES('BP', 'Air Botswana', 'Botswana');
INSERT INTO airline VALUES('BQ', 'Baltia Air Lines', 'United States');
INSERT INTO airline VALUES('BR', 'EVA Air', 'Taiwan');
INSERT INTO airline VALUES('BS', 'British International Helicopters', 'United Kingdom');
INSERT INTO airline VALUES('BT', 'Air Baltic', 'Latvia');
INSERT INTO airline VALUES('BU', 'Buryat Airlines Aircompany', 'Russia');
INSERT INTO airline VALUES('BV', 'Blue Panorama Airlines', 'Italy');
INSERT INTO airline VALUES('BW', 'Caribbean Airlines', 'Trinidad and Tobago');
INSERT INTO airline VALUES('BX', 'Air Busan', 'South Korea');
INSERT INTO airline VALUES('BY', 'TUI  Airways', 'United Kingdom');
INSERT INTO airline VALUES('BZ', 'Keystone Air Service', 'Canada');
INSERT INTO airline VALUES('CA', 'Air China', 'China');
INSERT INTO airline VALUES('CB', 'Kalitta Charters II', 'United States');
INSERT INTO airline VALUES('CC', 'Air Atlanta Icelandic', 'Iceland');
INSERT INTO airline VALUES('CD', 'Corendon Dutch Airlines', 'Netherlands');
INSERT INTO airline VALUES('CE', 'Nationwide Airlines', 'South Africa');
INSERT INTO airline VALUES('CG', 'Airlines PNG', 'Papua New Guinea');
INSERT INTO airline VALUES('CH', 'Bemidji Airlines', 'United States');
INSERT INTO airline VALUES('CI', 'China Airlines', 'Taiwan');
INSERT INTO airline VALUES('CJ', 'BA CityFlyer', 'United Kingdom');
INSERT INTO airline VALUES('CL', 'Lufthansa CityLine', 'Germany');
INSERT INTO airline VALUES('CM', 'Copa Airlines', 'Panama');
INSERT INTO airline VALUES('CN', 'Westward Airways', 'United States');
INSERT INTO airline VALUES('CO', 'Continental Airlines', 'United States');
INSERT INTO airline VALUES('CP', 'Canadian Pacific Airlines', 'Canada');
INSERT INTO airline VALUES('CQ', 'Central Charter', 'Czech Republic');
INSERT INTO airline VALUES('CS', 'Continental Micronesia', 'United States');
INSERT INTO airline VALUES('CU', 'Cubana de Aviación', 'Cuba');
INSERT INTO airline VALUES('CV', 'Air Chathams', 'New Zealand');
INSERT INTO airline VALUES('CW', 'Air Marshall Islands', 'Marshall Islands');
INSERT INTO airline VALUES('CX', 'Cathay Pacific', 'Hong Kong');
INSERT INTO airline VALUES('CY', 'Cyprus Airways', 'Cyprus');
INSERT INTO airline VALUES('CZ', 'China Southern Airlines', 'China');
INSERT INTO airline VALUES('DA', 'Air Georgia', 'Georgia');
INSERT INTO airline VALUES('DB', 'Brit Air', 'France');
INSERT INTO airline VALUES('DC', 'Golden Air', 'Sweden');
INSERT INTO airline VALUES('DD', 'Nok Air', 'Thailand');
INSERT INTO airline VALUES('DE', 'Condor Flugdienst', 'Germany');
INSERT INTO airline VALUES('DG', 'Cebgo', 'Philippines');
INSERT INTO airline VALUES('DH', 'Norwegian Air Norway', 'Norway');
INSERT INTO airline VALUES('DI', 'Dba', 'Germany');
INSERT INTO airline VALUES('DJ', 'Star Air', 'Denmark');
INSERT INTO airline VALUES('DK', 'Eastland Air', 'Australia');
INSERT INTO airline VALUES('DL', 'Delta Air Lines', 'United States');
INSERT INTO airline VALUES('DN', 'Norwegian Air Argentina', 'Argentina');
INSERT INTO airline VALUES('DP', 'Pobeda', 'Russia');
INSERT INTO airline VALUES('DQ', 'Coastal Air', 'United States');
INSERT INTO airline VALUES('DS', 'easyJet Switzerland', 'Switzerland');
INSERT INTO airline VALUES('DT', 'TAAG Angola Airlines', 'Angola');
INSERT INTO airline VALUES('DU', 'Norwegian Long Haul', 'Norway');
INSERT INTO airline VALUES('DV', 'Nantucket Airlines', 'United States');
INSERT INTO airline VALUES('DW', 'Aero-Charter Ukraine', 'Ukraine');
INSERT INTO airline VALUES('DX', 'DAT Danish Air Transport', 'Denmark');
INSERT INTO airline VALUES('DY', 'Norwegian Air Shuttle', 'Norway');
INSERT INTO airline VALUES('DZ', 'Donghai Airlines', 'China');
INSERT INTO airline VALUES('EA', 'European Air Express', 'Germany');
INSERT INTO airline VALUES('EC', 'easyJet Europe', 'Austria');
INSERT INTO airline VALUES('ED', 'AirExplore', 'Slovakia');
INSERT INTO airline VALUES('EG', 'Aer Lingus UK', 'United Kingdom');
INSERT INTO airline VALUES('EH', 'SAETA', 'Ecuador');
INSERT INTO airline VALUES('EI', 'Aer Lingus', 'Ireland');
INSERT INTO airline VALUES('EJ', 'New England Airlines', 'United States');
INSERT INTO airline VALUES('EK', 'Emirates Airlines', 'United Arab Emirates');
INSERT INTO airline VALUES('EL', 'Air Nippon', 'Japan');
INSERT INTO airline VALUES('EM', 'Empire Airlines', 'United States');
INSERT INTO airline VALUES('EN', 'Air Dolomiti', 'Italy');
INSERT INTO airline VALUES('EO', 'Hewa Bora Airways', 'Democratic Republic of the Congo');
INSERT INTO airline VALUES('EP', 'Iran Aseman Airlines', 'Iran');
INSERT INTO airline VALUES('EQ', 'TAME', 'Ecuador');
INSERT INTO airline VALUES('ES', 'DHL International', 'Bahrain');
INSERT INTO airline VALUES('ET', 'Ethiopian Airlines', 'Ethiopia');
INSERT INTO airline VALUES('EU', 'Empresa Ecuatoriana De Aviación', 'Ecuador');
INSERT INTO airline VALUES('EV', 'ExpressJet', 'United States');
INSERT INTO airline VALUES('EW', 'Eurowings', 'Germany');
INSERT INTO airline VALUES('EX', 'Atlantic Airlines', 'United States');
INSERT INTO airline VALUES('EY', 'Etihad Airways', 'United Arab Emirates');
INSERT INTO airline VALUES('EZ', 'Evergreen International Airlines', 'United States');
INSERT INTO airline VALUES('FA', 'Safair', 'South Africa');
INSERT INTO airline VALUES('FB', 'Bulgaria Air', 'Bulgaria');
INSERT INTO airline VALUES('FC', 'Finncomm Airlines', 'Finland');
INSERT INTO airline VALUES('FD', 'Thai  AirAsia', 'Thailand');
INSERT INTO airline VALUES('FE', 'Far Eastern Air Transport', 'Taiwan');
INSERT INTO airline VALUES('FF', 'Airshop', 'Netherlands');
INSERT INTO airline VALUES('FG', 'Ariana Afghan Airlines', 'Afghanistan');
INSERT INTO airline VALUES('FH', 'Freebird Airlines', 'Turkey');
INSERT INTO airline VALUES('FI', 'Icelandair', 'Iceland');
INSERT INTO airline VALUES('FJ', 'Fiji Airways', 'Fiji');
INSERT INTO airline VALUES('FK', 'Keewatin Air', 'Canada');
INSERT INTO airline VALUES('FL', 'Air Leap', 'Sweden');
INSERT INTO airline VALUES('FM', 'Shanghai Airlines', 'China');
INSERT INTO airline VALUES('FN', 'Regional Air Lines', 'Morocco');
INSERT INTO airline VALUES('FO', 'Airlines of Tasmania', 'Australia');
INSERT INTO airline VALUES('FP', 'Freedom Air', 'United States');
INSERT INTO airline VALUES('FR', 'Ryanair', 'Ireland');
INSERT INTO airline VALUES('FS', 'Flyr', 'Norway');
INSERT INTO airline VALUES('FT', 'FlyEgypt', 'Egypt');
INSERT INTO airline VALUES('FV', 'Rossiya', 'Russia');
INSERT INTO airline VALUES('FW', 'Ibex Airlines', 'Japan');
INSERT INTO airline VALUES('FX', 'FedEx Express', 'United States');
INSERT INTO airline VALUES('FY', 'Firefly', 'Malaysia');
INSERT INTO airline VALUES('FZ', 'Flydubai', 'United Arab Emirates');
INSERT INTO airline VALUES('GA', 'Garuda Indonesia', 'Indonesia');
INSERT INTO airline VALUES('GB', 'Airborne Express', 'United States');
INSERT INTO airline VALUES('GC', 'Gambia International Airlines', 'The Gambia');
INSERT INTO airline VALUES('GD', 'Air Alpha Greenland', 'Denmark');
INSERT INTO airline VALUES('GF', 'Gulf Air', 'Bahrain');
INSERT INTO airline VALUES('GG', 'Air Comores International', 'Comoros');
INSERT INTO airline VALUES('GH', 'Globus Airlines', 'Russia');
INSERT INTO airline VALUES('GI', 'Itek Air', 'Kyrgyzstan');
INSERT INTO airline VALUES('GJ', 'Loong Air', 'China');
INSERT INTO airline VALUES('GK', 'Jetstar Japan', 'Japan');
INSERT INTO airline VALUES('GL', 'Air Greenland', 'Greenland');
INSERT INTO airline VALUES('GM', 'Air Slovakia', 'Slovakia');
INSERT INTO airline VALUES('GP', 'Palau Trans Pacific Airlines', 'Palau');
INSERT INTO airline VALUES('GQ', 'Big Sky Airlines', 'United States');
INSERT INTO airline VALUES('GR', 'Aurigny Air Services', 'United Kingdom');
INSERT INTO airline VALUES('GS', 'Tianjin  Airlines', 'China');
INSERT INTO airline VALUES('GT', 'GB Airways', 'United Kingdom');
INSERT INTO airline VALUES('GV', 'Grant Aviation', 'United States');
INSERT INTO airline VALUES('GW', 'Costa Rica Green Airways', 'Costa Rica');
INSERT INTO airline VALUES('GX', 'Pacificair', 'Philippines');
INSERT INTO airline VALUES('GY', 'Tri-MG Intra Asia Airlines', 'Indonesia');
INSERT INTO airline VALUES('GZ', 'Air Rarotonga', 'Cook Islands');
INSERT INTO airline VALUES('HA', 'Hawaiian Airlines', 'United States');
INSERT INTO airline VALUES('HB', 'Harbor Airlines', 'United States');
INSERT INTO airline VALUES('HC', 'Air Senegal', 'Senegal');
INSERT INTO airline VALUES('HD', 'AIRDO', 'Japan');
INSERT INTO airline VALUES('HE', 'German Airways', 'Germany');
INSERT INTO airline VALUES('HF', 'Hapagfly', 'Germany');
INSERT INTO airline VALUES('HG', 'Niki', 'Austria');
INSERT INTO airline VALUES('HH', 'Hope Air', 'Canada');
INSERT INTO airline VALUES('HJ', 'Hellas Jet', 'Greece');
INSERT INTO airline VALUES('HM', 'Air Seychelles', 'Seychelles');
INSERT INTO airline VALUES('HO', 'Juneyao Air', 'China');
INSERT INTO airline VALUES('HP', 'America West Airlines', 'United States');
INSERT INTO airline VALUES('HQ', 'Harmony Airways', 'Canada');
INSERT INTO airline VALUES('HR', 'Hahn Air', 'Germany');
INSERT INTO airline VALUES('HU', 'Hainan Airlines', 'China');
INSERT INTO airline VALUES('HV', 'Transavia Holland', 'Netherlands');
INSERT INTO airline VALUES('HX', 'Hong Kong Airlines', 'Hong Kong');
INSERT INTO airline VALUES('HY', 'Uzbekistan Airways', 'Uzbekistan');
INSERT INTO airline VALUES('HZ', 'Sat Airlines', 'Kazakhstan');
INSERT INTO airline VALUES('IA', 'Iraqi Airways', 'Iraq');
INSERT INTO airline VALUES('IB', 'Iberia Airlines', 'Spain');
INSERT INTO airline VALUES('IC', 'Indian Airlines', 'India');
INSERT INTO airline VALUES('ID', 'Interlink Airlines', 'South Africa');
INSERT INTO airline VALUES('IE', 'Solomon Airlines', 'Solomon Islands');
INSERT INTO airline VALUES('IF', 'Islas Airways', 'Spain');
INSERT INTO airline VALUES('IG', 'Air Italy', 'Italy');
INSERT INTO airline VALUES('IH', 'Falcon Aviation', 'Sweden');
INSERT INTO airline VALUES('II', 'IBC Airways', 'United States');
INSERT INTO airline VALUES('IJ', 'Spring Airlines Japan', 'Japan');
INSERT INTO airline VALUES('IK', 'Ikar', 'Russia');
INSERT INTO airline VALUES('IM', 'Menajet', 'Lebanon');
INSERT INTO airline VALUES('IN', 'NAM Air', 'Indonesia');
INSERT INTO airline VALUES('IO', 'Indonesian Airlines', 'Indonesia');
INSERT INTO airline VALUES('IP', 'One Airlines', 'Chile');
INSERT INTO airline VALUES('IR', 'Iran Air', 'Iran');
INSERT INTO airline VALUES('IT', 'Tigerair  Taiwan', 'Taiwan');
INSERT INTO airline VALUES('IV', 'Wind Jet', 'Italy');
INSERT INTO airline VALUES('IW', 'Wings Air', 'Indonesia');
INSERT INTO airline VALUES('IX', 'Air India Express', 'India');
INSERT INTO airline VALUES('IY', 'Yemenia', 'Yemen');
INSERT INTO airline VALUES('IZ', 'Arkia Israel Airlines', 'Israel');
INSERT INTO airline VALUES('JA', 'JetSMART', 'Chile');
INSERT INTO airline VALUES('JB', 'Helijet', 'Canada');
INSERT INTO airline VALUES('JC', 'JAL Express', 'Japan');
INSERT INTO airline VALUES('JD', 'Beijing Capital Airlines', 'China');
INSERT INTO airline VALUES('JE', 'Mango', 'South Africa');
INSERT INTO airline VALUES('JF', 'Jet Asia Airways', 'Thailand');
INSERT INTO airline VALUES('JH', 'Nordeste Linhas Aéreas Regionais', 'Brazil');
INSERT INTO airline VALUES('JJ', 'LATAM  Brasil', 'Brazil');
INSERT INTO airline VALUES('JL', 'Japan Airlines', 'Japan');
INSERT INTO airline VALUES('JM', 'Air Jamaica', 'Jamaica');
INSERT INTO airline VALUES('JN', 'Excel Airways', 'United Kingdom');
INSERT INTO airline VALUES('JO', 'Jettime', 'Denmark');
INSERT INTO airline VALUES('JQ', 'Jetstar', 'Australia');
INSERT INTO airline VALUES('JR', 'Aero California', 'Mexico');
INSERT INTO airline VALUES('JS', 'Air Koryo', 'Democratic People\'s Republic of Korea');
INSERT INTO airline VALUES('JT', 'Lion Air', 'Indonesia');
INSERT INTO airline VALUES('JU', 'Jat Airways', 'Serbia');
INSERT INTO airline VALUES('JV', 'Bearskin Lake Air Service', 'Canada');
INSERT INTO airline VALUES('JW', 'Vanilla Air', 'Japan');
INSERT INTO airline VALUES('JX', 'Starlux Airlines', 'Taiwan');
INSERT INTO airline VALUES('JY', 'Air Turks and Caicos', 'Turks and Caicos Islands');
INSERT INTO airline VALUES('JZ', 'JetSMART Perú', 'Peru');
INSERT INTO airline VALUES('KB', 'Druk Air', 'Bhutan');
INSERT INTO airline VALUES('KC', 'Air Astana', 'Kazakhstan');
INSERT INTO airline VALUES('KD', 'KD Avia', 'Russia');
INSERT INTO airline VALUES('KE', 'Korean Air', 'South Korea');
INSERT INTO airline VALUES('KF', 'Blue1', 'Finland');
INSERT INTO airline VALUES('KG', 'Key Lime Air', 'United States');
INSERT INTO airline VALUES('KI', 'Air Atlantique', 'United Kingdom');
INSERT INTO airline VALUES('KJ', 'Air Incheon', 'South Korea');
INSERT INTO airline VALUES('KK', 'Atlasjet', 'Turkey');
INSERT INTO airline VALUES('KL', 'KLM', 'Netherlands');
INSERT INTO airline VALUES('KM', 'Air Malta', 'Malta');
INSERT INTO airline VALUES('KN', 'China United Airlines', 'China');
INSERT INTO airline VALUES('KO', 'Alaska Central Express', 'United States');
INSERT INTO airline VALUES('KP', 'Kiwi International Air Lines', 'United States');
INSERT INTO airline VALUES('KQ', 'Kenya Airways', 'Kenya');
INSERT INTO airline VALUES('KR', 'Cambodia Airways', 'Cambodia');
INSERT INTO airline VALUES('KS', 'Peninsula Airways', 'United States');
INSERT INTO airline VALUES('KU', 'Kuwait Airways', 'Kuwait');
INSERT INTO airline VALUES('KV', 'Kavminvodyavia', 'Russia');
INSERT INTO airline VALUES('KW', 'Kelowna Flightcraft Air Charter', 'Canada');
INSERT INTO airline VALUES('KX', 'Cayman Airways', 'Cayman Islands');
INSERT INTO airline VALUES('KY', 'Kunming Airlines', 'China');
INSERT INTO airline VALUES('LA', 'LATAM Chile', 'Chile');
INSERT INTO airline VALUES('LB', 'Air Costa', 'India');
INSERT INTO airline VALUES('LD', 'Air Hong Kong', 'Hong Kong');
INSERT INTO airline VALUES('LF', 'Contour Airlines', 'United States');
INSERT INTO airline VALUES('LG', 'Luxair', 'Luxembourg');
INSERT INTO airline VALUES('LH', 'Lufthansa', 'Germany');
INSERT INTO airline VALUES('LI', 'Leeward Islands Air Transport', 'Antigua and Barbuda');
INSERT INTO airline VALUES('LJ', 'Jin Air', 'South Korea');
INSERT INTO airline VALUES('LK', 'Air Luxor', 'Portugal');
INSERT INTO airline VALUES('LL', 'Miami Air International', 'United States');
INSERT INTO airline VALUES('LM', 'Livingston Energy Flight', 'Italy');
INSERT INTO airline VALUES('LN', 'Libyan Arab Airlines', 'Libya');
INSERT INTO airline VALUES('LO', 'LOT Polish Airlines', 'Poland');
INSERT INTO airline VALUES('LP', 'LATAM Peru', 'Peru');
INSERT INTO airline VALUES('LQ', 'Lebanese Air Transport', 'Lebanon');
INSERT INTO airline VALUES('LR', 'LACSA', 'Costa Rica');
INSERT INTO airline VALUES('LS', 'Jet2.com', 'United Kingdom');
INSERT INTO airline VALUES('LT', 'LongJiang Airlines', 'China');
INSERT INTO airline VALUES('LU', 'LATAM Express', 'Chile');
INSERT INTO airline VALUES('LV', 'Albanian Airlines', 'Albania');
INSERT INTO airline VALUES('LW', 'Sun Air International', 'United States');
INSERT INTO airline VALUES('LX', 'Swiss International Air Lines', 'Switzerland');
INSERT INTO airline VALUES('LY', 'El Al Israel Airlines', 'Israel');
INSERT INTO airline VALUES('MB', 'Execair Aviation', 'Canada');
INSERT INTO airline VALUES('MC', 'Air Mobility Command', 'United States');
INSERT INTO airline VALUES('MD', 'Air Madagascar', 'Madagascar');
INSERT INTO airline VALUES('ME', 'Middle East Airlines', 'Lebanon');
INSERT INTO airline VALUES('MF', 'Xiamen Airlines', 'China');
INSERT INTO airline VALUES('MG', 'Champion Air', 'United States');
INSERT INTO airline VALUES('MH', 'Malaysia Airlines', 'Malaysia');
INSERT INTO airline VALUES('MI', 'SilkAir', 'Singapore');
INSERT INTO airline VALUES('MJ', 'Mihin Lanka', 'Sri Lanka');
INSERT INTO airline VALUES('MK', 'Air Mauritius', 'Mauritius');
INSERT INTO airline VALUES('ML', 'African Transport Trading and Investment Company', 'Sudan');
INSERT INTO airline VALUES('MM', 'EuroAtlantic Airways', 'Portugal');
INSERT INTO airline VALUES('MN', 'Comair', 'South Africa');
INSERT INTO airline VALUES('MO', 'Presidential Flight', 'United Arab Emirates');
INSERT INTO airline VALUES('MP', 'Martinair', 'Netherlands');
INSERT INTO airline VALUES('MQ', 'Envoy Air', 'United States');
INSERT INTO airline VALUES('MR', 'Hunnu Air', 'Mongolia');
INSERT INTO airline VALUES('MS', 'Egyptair', 'Egypt');
INSERT INTO airline VALUES('MT', 'Thomas Cook Airlines', 'United Kingdom');
INSERT INTO airline VALUES('MU', 'China Eastern Airlines', 'China');
INSERT INTO airline VALUES('MV', 'Air Mediterranean', 'Greece');
INSERT INTO airline VALUES('MW', 'Mokulele Airlines', 'United States');
INSERT INTO airline VALUES('MX', 'Breeze Airways', 'United States');
INSERT INTO airline VALUES('MY', 'Midwest Airlines (Egypt)', 'Egypt');
INSERT INTO airline VALUES('MZ', 'Merpati Nusantara Airlines', 'Indonesia');
INSERT INTO airline VALUES('NB', 'Sterling Airlines', 'Denmark');
INSERT INTO airline VALUES('NC', 'National Jet Express', 'Australia');
INSERT INTO airline VALUES('NE', 'Nesma Airlines', 'Egypt');
INSERT INTO airline VALUES('NF', 'Air Vanuatu', 'Vanuatu');
INSERT INTO airline VALUES('NG', 'Lauda Air', 'Austria');
INSERT INTO airline VALUES('NH', 'All Nippon Airways', 'Japan');
INSERT INTO airline VALUES('NI', 'LANICA', 'Nicaragua');
INSERT INTO airline VALUES('NK', 'Spirit Airlines', 'United States');
INSERT INTO airline VALUES('NL', 'Shaheen Air', 'Pakistan');
INSERT INTO airline VALUES('NM', 'Mount Cook Airline', 'New Zealand');
INSERT INTO airline VALUES('NN', 'VIM Airlines', 'Russia');
INSERT INTO airline VALUES('NO', 'Neos', 'Italy');
INSERT INTO airline VALUES('NP', 'Nile Air', 'Egypt');
INSERT INTO airline VALUES('NQ', 'Air Japan', 'Japan');
INSERT INTO airline VALUES('NR', 'Pamir Airways', 'Afghanistan');
INSERT INTO airline VALUES('NS', 'Hebei Airlines', 'China');
INSERT INTO airline VALUES('NT', 'Binter Canarias', 'Spain');
INSERT INTO airline VALUES('NU', 'Japan Transocean Air', 'Japan');
INSERT INTO airline VALUES('NV', 'Air Central', 'Japan');
INSERT INTO airline VALUES('NX', 'Air Macau', 'Macao');
INSERT INTO airline VALUES('NY', 'Air Iceland', 'Iceland');
INSERT INTO airline VALUES('NZ', 'Air New Zealand', 'New Zealand');
INSERT INTO airline VALUES('OA', 'Olympic Air', 'Greece');
INSERT INTO airline VALUES('OB', 'Oasis International Airlines', 'Spain');
INSERT INTO airline VALUES('OD', 'Malindo Airways', 'Malaysia');
INSERT INTO airline VALUES('OE', 'Asia Overnight Express', 'Philippines');
INSERT INTO airline VALUES('OF', 'Air Finland', 'Finland');
INSERT INTO airline VALUES('OG', 'Play', 'Iceland');
INSERT INTO airline VALUES('OH', 'Comair', 'United States');
INSERT INTO airline VALUES('OJ', 'Overland Airways', 'Nigeria');
INSERT INTO airline VALUES('OK', 'Czech Airlines', 'Czech Republic');
INSERT INTO airline VALUES('OL', 'OLT Express Germany', 'Germany');
INSERT INTO airline VALUES('OM', 'MIAT Mongolian Airlines', 'Mongolia');
INSERT INTO airline VALUES('ON', 'Our Airline', 'Nauru');
INSERT INTO airline VALUES('OO', 'SkyWest Airlines', 'United States');
INSERT INTO airline VALUES('OP', 'Chalk\'s International Airlines', 'United States');
INSERT INTO airline VALUES('OQ', 'Chongqing Airlines', 'China');
INSERT INTO airline VALUES('OR', 'TUI fly Netherlands', 'Netherlands');
INSERT INTO airline VALUES('OS', 'Austrian Airlines', 'Austria');
INSERT INTO airline VALUES('OT', 'Aeropelican Air Services', 'Australia');
INSERT INTO airline VALUES('OU', 'Croatia Airlines', 'Croatia');
INSERT INTO airline VALUES('OV', 'Estonian Air', 'Estonia');
INSERT INTO airline VALUES('OW', 'Executive Airlines', 'United States');
INSERT INTO airline VALUES('OX', 'Orient Thai Airlines', 'Thailand');
INSERT INTO airline VALUES('OY', 'Andes Líneas Aéreas', 'Argentina');
INSERT INTO airline VALUES('OZ', 'Asiana Airlines', 'South Korea');
INSERT INTO airline VALUES('PA', 'Florida Coastal Airlines', 'United States');
INSERT INTO airline VALUES('PB', 'Provincial Airlines', 'Canada');
INSERT INTO airline VALUES('PC', 'Pegasus Airlines', 'Turkey');
INSERT INTO airline VALUES('PD', 'Porter Airlines', 'Canada');
INSERT INTO airline VALUES('PE', 'People\'s', 'Austria');
INSERT INTO airline VALUES('PF', 'Palestinian Airlines', 'Egypt');
INSERT INTO airline VALUES('PG', 'Bangkok Airways', 'Thailand');
INSERT INTO airline VALUES('PH', 'Polynesian Airlines', 'Samoa');
INSERT INTO airline VALUES('PI', 'Sol del Paraguay', 'Paraguay');
INSERT INTO airline VALUES('PJ', 'Air Saint Pierre', 'France');
INSERT INTO airline VALUES('PK', 'Pakistan International Airlines', 'Pakistan');
INSERT INTO airline VALUES('PM', 'Tropic Air', 'Belize');
INSERT INTO airline VALUES('PN', 'West Air (China)', 'China');
INSERT INTO airline VALUES('PP', 'Jet Aviation', 'Switzerland');
INSERT INTO airline VALUES('PQ', 'SkyUp', 'Ukraine');
INSERT INTO airline VALUES('PR', 'Philippine Airlines', 'Philippines');
INSERT INTO airline VALUES('PS', 'Ukraine International Airlines', 'Ukraine');
INSERT INTO airline VALUES('PU', 'PLUNA', 'Uruguay');
INSERT INTO airline VALUES('PV', 'St Barth Commuter', 'France');
INSERT INTO airline VALUES('PW', 'Precision Air', 'Tanzania');
INSERT INTO airline VALUES('PX', 'Air Niugini', 'Papua New Guinea');
INSERT INTO airline VALUES('PY', 'Surinam Airways', 'Suriname');
INSERT INTO airline VALUES('PZ', 'TAM  Mercosur', 'Paraguay');
INSERT INTO airline VALUES('QB', 'Air Alma', 'Canada');
INSERT INTO airline VALUES('QC', 'Camair-Co', 'Cameroon');
INSERT INTO airline VALUES('QD', 'Air Class Líneas Aéreas', 'Uruguay');
INSERT INTO airline VALUES('QE', 'Crossair Europe', 'Switzerland');
INSERT INTO airline VALUES('QF', 'Qantas', 'Australia');
INSERT INTO airline VALUES('QH', 'Air Kyrgyzstan', 'Kyrgyzstan');
INSERT INTO airline VALUES('QI', 'Cimber Sterling', 'Denmark');
INSERT INTO airline VALUES('QJ', 'Jet Airways', 'United States');
INSERT INTO airline VALUES('QK', 'Air Canada Jazz', 'Canada');
INSERT INTO airline VALUES('QL', 'Línea Aérea de Servicio Ejecutivo Regional', 'Venezuela');
INSERT INTO airline VALUES('QN', 'Air Armenia', 'Armenia');
INSERT INTO airline VALUES('QO', 'Origin Pacific Airways', 'New Zealand');
INSERT INTO airline VALUES('QP', 'Akasa Air', 'India');
INSERT INTO airline VALUES('QQ', 'Alliance Airlines', 'Australia');
INSERT INTO airline VALUES('QR', 'Qatar Airways', 'Qatar');
INSERT INTO airline VALUES('QS', 'Smartwings', 'Czech Republic');
INSERT INTO airline VALUES('QT', 'TAMPA', 'Colombia');
INSERT INTO airline VALUES('QU', 'UTair-Ukraine', 'Ukraine');
INSERT INTO airline VALUES('QV', 'Lao Airlines', 'Laos');
INSERT INTO airline VALUES('QW', 'Qingdao Airlines', 'China');
INSERT INTO airline VALUES('QX', 'Horizon Air', 'United States');
INSERT INTO airline VALUES('QY', 'European Air Transport', 'Belgium');
INSERT INTO airline VALUES('QZ', 'Indonesia AirAsia', 'Indonesia');
INSERT INTO airline VALUES('RA', 'Nepal Airlines', 'Nepal');
INSERT INTO airline VALUES('RB', 'Syrian Arab Airlines', 'Syria');
INSERT INTO airline VALUES('RE', 'Stobart Air', 'Ireland');
INSERT INTO airline VALUES('RF', 'Aero K', 'South Korea');
INSERT INTO airline VALUES('RG', 'Varig', 'Brazil');
INSERT INTO airline VALUES('RH', 'Republic Express Airlines', 'Indonesia');
INSERT INTO airline VALUES('RI', 'Mandala Airlines', 'Indonesia');
INSERT INTO airline VALUES('RJ', 'Royal Jordanian', 'Jordan');
INSERT INTO airline VALUES('RK', 'Ryanair UK', 'United Kingdom');
INSERT INTO airline VALUES('RL', 'Rio Linhas Aéreas', 'Brazil');
INSERT INTO airline VALUES('RO', 'Tarom', 'Romania');
INSERT INTO airline VALUES('RP', 'Chautauqua Airlines', 'United States');
INSERT INTO airline VALUES('RQ', 'Kam Air', 'Afghanistan');
INSERT INTO airline VALUES('RR', 'Buzz (Ryanair)', 'Poland');
INSERT INTO airline VALUES('RS', 'Air Seoul', 'South Korea');
INSERT INTO airline VALUES('RT', 'UVT Aero', 'Russia');
INSERT INTO airline VALUES('RU', 'SkyKing Turks and Caicos Airways', 'Turks and Caicos Islands');
INSERT INTO airline VALUES('RV', 'Africaone', 'The Gambia');
INSERT INTO airline VALUES('RW', 'Republic Airways', 'United States');
INSERT INTO airline VALUES('RX', 'Riyadh Air', 'Saudi Arabia');
INSERT INTO airline VALUES('RZ', 'Sansa', 'Costa Rica');
INSERT INTO airline VALUES('SA', 'South African Airways', 'South Africa');
INSERT INTO airline VALUES('SB', 'Air Caledonie International', 'France');
INSERT INTO airline VALUES('SC', 'Shandong Airlines', 'China');
INSERT INTO airline VALUES('SD', 'Sudan Airways', 'Sudan');
INSERT INTO airline VALUES('SE', 'XL Airways France', 'France');
INSERT INTO airline VALUES('SF', 'Tassili  Airlines', 'Algeria');
INSERT INTO airline VALUES('SG', 'Spicejet', 'India');
INSERT INTO airline VALUES('SH', 'Fly Me Sweden', 'Sweden');
INSERT INTO airline VALUES('SI', 'Skynet Airlines', 'Ireland');
INSERT INTO airline VALUES('SK', 'Scandinavian Airlines', 'Sweden');
INSERT INTO airline VALUES('SL', 'Thai  Lion Mentari', 'Thailand');
INSERT INTO airline VALUES('SM', 'Swedline Express', 'Sweden');
INSERT INTO airline VALUES('SN', 'Brussels Airlines', 'Belgium');
INSERT INTO airline VALUES('SO', 'Sosoliso Airlines', 'Nigeria');
INSERT INTO airline VALUES('SP', 'SATA Air Acores', 'Portugal');
INSERT INTO airline VALUES('SQ', 'Singapore Airlines', 'Singapore');
INSERT INTO airline VALUES('SR', 'Sundair', 'Germany');
INSERT INTO airline VALUES('SS', 'Corsairfly', 'France');
INSERT INTO airline VALUES('ST', 'Germania', 'Germany');
INSERT INTO airline VALUES('SU', 'Aeroflot', 'Russia');
INSERT INTO airline VALUES('SV', 'Saudia', 'Saudi Arabia');
INSERT INTO airline VALUES('SX', 'FlyGTA Airlines', 'Canada');
INSERT INTO airline VALUES('SY', 'Sun Country Airlines', 'United States');
INSERT INTO airline VALUES('TB', 'TUI  fly Belgium', 'Belgium');
INSERT INTO airline VALUES('TC', 'Air Tanzania', 'Tanzania');
INSERT INTO airline VALUES('TD', 'Tulip Air', 'Netherlands');
INSERT INTO airline VALUES('TE', 'Skytaxi', 'Poland');
INSERT INTO airline VALUES('TF', 'Malmö Aviation', 'Sweden');
INSERT INTO airline VALUES('TG', 'Thai Airways International', 'Thailand');
INSERT INTO airline VALUES('TH', 'Raya Airways', 'Malaysia');
INSERT INTO airline VALUES('TI', 'Tailwind Airlines', 'Turkey');
INSERT INTO airline VALUES('TJ', 'Tradewind Aviation', 'United States');
INSERT INTO airline VALUES('TK', 'Turkish  Airlines', 'Turkey');
INSERT INTO airline VALUES('TL', 'Trans  Mediterranean Airlines', 'Lebanon');
INSERT INTO airline VALUES('TM', 'Linhas Aéreas de Moçambique', 'Mozambique');
INSERT INTO airline VALUES('TN', 'Air Tahiti Nui', 'France');
INSERT INTO airline VALUES('TO', 'President Airlines', 'Cambodia');
INSERT INTO airline VALUES('TP', 'TAP  Portugal', 'Portugal');
INSERT INTO airline VALUES('TQ', 'Tandem  Aero', 'Moldova');
INSERT INTO airline VALUES('TR', 'Scoot', 'Singapore');
INSERT INTO airline VALUES('TS', 'Air Transat', 'Canada');
INSERT INTO airline VALUES('TT', 'Tigerair Australia', 'Australia');
INSERT INTO airline VALUES('TU', 'Tunisair', 'Tunisia');
INSERT INTO airline VALUES('TW', 'Trans World Airlines', 'United States');
INSERT INTO airline VALUES('TX', 'Thai Express Air', 'Thailand');
INSERT INTO airline VALUES('TY', 'Air Calédonie', 'France');
INSERT INTO airline VALUES('TZ', 'Tsaradia', 'Madagascar');
INSERT INTO airline VALUES('UA', 'United Airlines', 'United States');
INSERT INTO airline VALUES('UB', 'Myanma Airways', 'Myanmar');
INSERT INTO airline VALUES('UD', 'Hex Air', 'France');
INSERT INTO airline VALUES('UE', 'Nasair', 'Eritrea');
INSERT INTO airline VALUES('UF', 'UM Airlines', 'Ukraine');
INSERT INTO airline VALUES('UG', 'Tuninter', 'Tunisia');
INSERT INTO airline VALUES('UH', 'US Helicopter', 'United States');
INSERT INTO airline VALUES('UI', 'Eurocypria Airlines', 'Cyprus');
INSERT INTO airline VALUES('UJ', 'AlMasria Universal Airlines', 'Egypt');
INSERT INTO airline VALUES('UK', 'Vistara', 'India');
INSERT INTO airline VALUES('UL', 'SriLankan Airlines', 'Sri Lanka');
INSERT INTO airline VALUES('UM', 'Air Zimbabwe', 'Zimbabwe');
INSERT INTO airline VALUES('UN', 'Transaero Airlines', 'Russia');
INSERT INTO airline VALUES('UO', 'Hong Kong Express Airways', 'Hong Kong');
INSERT INTO airline VALUES('UP', 'Bahamasair', 'Bahamas');
INSERT INTO airline VALUES('UR', 'Uganda Airlines', 'Uganda');
INSERT INTO airline VALUES('US', 'Unavia Suisse', 'Switzerland');
INSERT INTO airline VALUES('UT', 'UTair Aviation', 'Russia');
INSERT INTO airline VALUES('UU', 'Air Austral', 'France');
INSERT INTO airline VALUES('UX', 'Air Europa', 'Spain');
INSERT INTO airline VALUES('UZ', 'El-Buraq Air Transport', 'Libya');
INSERT INTO airline VALUES('VA', 'Virgin Australia', 'Australia');
INSERT INTO airline VALUES('VB', 'Aeroenlaces Nacionales', 'Mexico');
INSERT INTO airline VALUES('VC', 'Voyageur Airways', 'Canada');
INSERT INTO airline VALUES('VD', 'Kunpeng Airlines', 'China');
INSERT INTO airline VALUES('VE', 'C.A.I. Second', 'Italy');
INSERT INTO airline VALUES('VF', 'AJet', 'Turkey');
INSERT INTO airline VALUES('VH', 'Viva Air Colombia', 'Colombia');
INSERT INTO airline VALUES('VI', 'Volga-Dnepr Airlines', 'Russia');
INSERT INTO airline VALUES('VJ', 'Jatayu Airlines', 'Indonesia');
INSERT INTO airline VALUES('VK', 'Virgin Nigeria Airways', 'Nigeria');
INSERT INTO airline VALUES('VL', 'City Airlines', 'Germany');
INSERT INTO airline VALUES('VM', 'Viaggio Air', 'Bulgaria');
INSERT INTO airline VALUES('VN', 'Vietnam Airlines', 'Vietnam');
INSERT INTO airline VALUES('VO', 'Tyrolean  Airways', 'Austria');
INSERT INTO airline VALUES('VQ', 'Novo Air', 'Bangladesh');
INSERT INTO airline VALUES('VS', 'Virgin Atlantic', 'United Kingdom');
INSERT INTO airline VALUES('VT', 'Air Tahiti', 'France');
INSERT INTO airline VALUES('VU', 'Vietravel Airlines', 'Vietnam');
INSERT INTO airline VALUES('VW', 'Aeromar', 'Mexico');
INSERT INTO airline VALUES('VX', 'Virgin America', 'United States');
INSERT INTO airline VALUES('VY', 'Vueling Airlines', 'Spain');
INSERT INTO airline VALUES('VZ', 'Thai  Vietjet Air', 'Thailand');
INSERT INTO airline VALUES('WA', 'KLM Cityhopper', 'Netherlands');
INSERT INTO airline VALUES('WB', 'Rwandair Express', 'Rwanda');
INSERT INTO airline VALUES('WC', 'Wien Air Alaska', 'United States');
INSERT INTO airline VALUES('WD', 'Amsterdam Airlines', 'Netherlands');
INSERT INTO airline VALUES('WE', 'Thai Smile  Airways', 'Thailand');
INSERT INTO airline VALUES('WF', 'Widerøe', 'Norway');
INSERT INTO airline VALUES('WG', 'Sunwing Airlines', 'Canada');
INSERT INTO airline VALUES('WH', 'WebJet Linhas Aéreas', 'Brazil');
INSERT INTO airline VALUES('WI', 'Aero Air', 'United States');
INSERT INTO airline VALUES('WJ', 'JetSMART Argentina', 'Argentina');
INSERT INTO airline VALUES('WK', 'Edelweiss Air', 'Switzerland');
INSERT INTO airline VALUES('WN', 'Southwest Airlines', 'United States');
INSERT INTO airline VALUES('WO', 'Swoop', 'Canada');
INSERT INTO airline VALUES('WQ', 'Swift Air (Interstate Equipment Leasing)', 'United States');
INSERT INTO airline VALUES('WR', 'WestJet Encore', 'Canada');
INSERT INTO airline VALUES('WS', 'WestJet', 'Canada');
INSERT INTO airline VALUES('WT', 'Wasaya Airways', 'Canada');
INSERT INTO airline VALUES('WV', 'Swe Fly', 'Sweden');
INSERT INTO airline VALUES('WW', 'WOW air', 'Iceland');
INSERT INTO airline VALUES('WX', 'CityJet', 'Ireland');
INSERT INTO airline VALUES('WY', 'Oman Air', 'Oman');
INSERT INTO airline VALUES('WZ', 'West African Airlines', 'Benin');
INSERT INTO airline VALUES('XC', 'Corendon Airlines', 'Turkey');
INSERT INTO airline VALUES('XE', 'JSX (airline)', 'United States');
INSERT INTO airline VALUES('XF', 'Vladivostok Air', 'Russia');
INSERT INTO airline VALUES('XG', 'Sunexpress Deutschland', 'Germany');
INSERT INTO airline VALUES('XJ', 'Mesaba Airlines', 'United States');
INSERT INTO airline VALUES('XK', 'Corse Méditerranée', 'France');
INSERT INTO airline VALUES('XL', 'Aerolane', 'Ecuador');
INSERT INTO airline VALUES('XM', 'Australian airExpress', 'Australia');
INSERT INTO airline VALUES('XN', 'XpressAir', 'Indonesia');
INSERT INTO airline VALUES('XO', 'China Xinhua Airlines', 'China');
INSERT INTO airline VALUES('XP', 'Avelo Airlines', 'United States');
INSERT INTO airline VALUES('XQ', 'SunExpress', 'Turkey');
INSERT INTO airline VALUES('XS', 'SITA', 'Belgium');
INSERT INTO airline VALUES('XT', 'SkyStar Airways', 'Thailand');
INSERT INTO airline VALUES('XV', 'Mississippi Valley Airlines', 'United States');
INSERT INTO airline VALUES('XW', 'NokScoot', 'Thailand');
INSERT INTO airline VALUES('XY', 'Flynas', 'Saudi Arabia');
INSERT INTO airline VALUES('YB', 'Borajet', 'Turkey');
INSERT INTO airline VALUES('YH', 'West Caribbean Airways', 'Colombia');
INSERT INTO airline VALUES('YI', 'Air Sunshine', 'United States');
INSERT INTO airline VALUES('YJ', 'AMC Airlines', 'Egypt');
INSERT INTO airline VALUES('YK', 'Cyprus Turkish Airlines', 'Turkey');
INSERT INTO airline VALUES('YL', 'Yamal Airlines', 'Russia');
INSERT INTO airline VALUES('YM', 'Montenegro Airlines', 'Montenegro');
INSERT INTO airline VALUES('YP', 'Air Premia', 'South Korea');
INSERT INTO airline VALUES('YQ', 'TAR Aerolineas', 'Mexico');
INSERT INTO airline VALUES('YS', 'Régional', 'France');
INSERT INTO airline VALUES('YT', 'Yeti Airlines', 'Nepal');
INSERT INTO airline VALUES('YV', 'Mesa Airlines', 'United States');
INSERT INTO airline VALUES('YW', 'Air Nostrum', 'Spain');
INSERT INTO airline VALUES('YX', 'Midwest Airlines', 'United States');
INSERT INTO airline VALUES('ZA', 'Interavia Airlines', 'Russia');
INSERT INTO airline VALUES('ZB', 'Air Albania', 'Albania');
INSERT INTO airline VALUES('ZD', 'Ewa Air', 'France');
INSERT INTO airline VALUES('ZE', 'Eastar Jet', 'South Korea');
INSERT INTO airline VALUES('ZG', 'Zipair Tokyo', 'Japan');
INSERT INTO airline VALUES('ZH', 'Shenzhen Airlines', 'China');
INSERT INTO airline VALUES('ZI', 'Aigle Azur', 'France');
INSERT INTO airline VALUES('ZK', 'Great Lakes Airlines', 'United States');
INSERT INTO airline VALUES('ZL', 'Regional Express', 'Australia');
INSERT INTO airline VALUES('ZN', 'Key Airlines', 'United States');
INSERT INTO airline VALUES('ZP', 'Silk Way Airlines', 'Azerbaijan');
INSERT INTO airline VALUES('ZS', 'Sama Airlines', 'Saudi Arabia');
INSERT INTO airline VALUES('ZT', 'Titan  Airways', 'United Kingdom');
INSERT INTO airline VALUES('ZW', 'Air Wisconsin', 'United States');
INSERT INTO airline VALUES('ZX', 'Air Georgian', 'Canada');
INSERT INTO airline VALUES('ZY', 'Sky Airlines', 'Turkey');